export default{
    Name:'Enter Your Name',
    HOME:'Home',
    PROFILE:'Profile',
    SEARCH:'Search',
    BY_CLICKING_LOG_IN:'By Clicking "Log In" You  agree With our',
    LEARN_HOW_WE_PROCESS:"Learn how we process your data in our",
    TERMS:"Terms",
    PRIVACY_POLICY:"Privacy policy",
    LOG_IN_WITH_PHONE:'Log In With Phone Number',
    OR:"or",
    LOGIN_WITH_GOOGLE:"Log In With Google",
    LOGIN_WITH_FACEBOOK:'Log In With FaceBook',
    NEW_HERE:"New here ?",
    SIGN_UP:"Sign UP",
    WelCome_BACk:'Welcome Back',
    WE_ARE_HAPPY_TO_SEE:'We Are Happy to see . You can login to continue',
    EMAIL:" Enter your Email",
    PASSWORD:" Enter your Pasword",
    SHOW:"Show",
    HIDE:"Hide",
    FORGOT_PASS:"Forgot Password ?",
    USE_OPT:"Use OTP",
    LOGIN:"Login",
    CREATE_NEW_ACCOUNT:"Create new account",
    CREATE_AN_ACCOUNT_SO_YOU_CAN_CONTINUE:"Create an account so that you can continue",
    USERNAME:"User name",
    FULL_NAME:"Full name",
    MOBILE_NUMBER:"Mobile number",
    CONFIRM_PASS:"Confirm Password",
    KEEP_ME_LOGGED_IN:"keep me logged in ",
    LOGGED_IN_YOUR_ACC:"Login  in  to  your  Account",
    DONT_HAVE_ACC:"Don't have an account?",
    ALREADY_HAVE_ACC:"Already have an account? ",
    SIGN_IN:'Sign in',
    REGISTER:"Register",
    REGISTER_TO_ACC:"Register to your account",
    ADDADDRESS:"Add Address"


}